### ISSUE TITLE
Improve Hardcoded Credentials Check via Entropy

### ISSUE THREAD

**Issue by endophage** [GoASTScanner/gas#105]
I've disabled the hardcoded credentials check for a number of projects we're running gas on because it's too noisy and has little value. It seems like (and let me know if I'm misunderstanding) it marks everything as confidence low. I'd be interested in adding an entropy check to threshold the confidence levels; high entropy = high confidence it's a password.

Just spitballing, but I'm thinking we could do something like calculate a shannon entropy value and work out some thresholds that would map to confidence levels. This might help highlight highly random strings where there is a good chance they are a password.

Also, in light of the new [NIST password guidelines](https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-verifiers), it would be interesting to supplement that with a dictionary of common passwords to match low entropy bad passwords with a higher confidence level.

**Comment by gcmurphy** [comment]
Sure I think that makes sense. This is something that I've been meaning to get to but haven't had a chance. I know the folks from  [Lyft used zcxvbn in a plugin](https://github.com/lyft/bandit-high-entropy-string) for a similar Python tool. We could probably do something similar here.

**Comment by endophage** [comment]
I see there's already a go port of zcxvbn so that might be the fastest option. I should have time to look at this next week (I'm taking some PTO so will have time to work on non-day-job stuff :-).

**Comment by gcmurphy** [comment]
The hardcoded entropy check has been included. I believe there are still optimizations and improvements we can do to this rule but closing this for now as it directly addresses the original issue.

**Comment by endophage** [comment]
Awesome! Sorry I never got back to this. Life happened...
