### ISSUE TITLE
what does 'Subprocess launching with variable.,HIGH,HIGH (gas)' mean ?

### ISSUE THREAD

**Issue by bruceauyeung** [GoASTScanner/gas#106]
for sample code 
```
echoCmd:="echo 123"
_, err := exec.Command("sh", "-c", echoCmd).Output()
```
why launching subprocess with variable is considered as an error / warning / code smell ?

**Comment by gcmurphy** [comment]
> G204: Audit use of command execution

I believe the intent of this rule is to assist when performing code audits of Go source code. It may not necessarily be an issue that introduces command injection but you may want to know which external executables are being called by an application when performing a security review.

**Comment by andradei** [comment]
I ran into the same warning even though my program had to run a command with arguments coming from a variable. I was happy with the warning regardless because it raised my awareness of a possible flaw.

**Comment by gcmurphy** [comment]
Agree. This can be addressed as apart of #127

**Comment by msudgh** [comment]
@gcmurphy I didn't see any workaround, How can I fix this warning?

**Comment by AnirudhVyas** [comment]
hello there - can the warning be fixed?

**Comment by gcmurphy** [comment]
Invoking `gosec -exclude=G204` will ignore this check for your entire project. Or you can annotate specific areas of the source code with a  `// #nosec` comment to avoid warning on that use case.  

This is covered in the [README.md](https://github.com/securego/gosec/blob/master/README.md).

**Comment by AnirudhVyas** [comment]
awesome, thanks!
