### ISSUE TITLE
Checkstyle output format 

### ISSUE THREAD

**Issue by chavacava** [GoASTScanner/gas#120]
Hi, 
I'm planning to incorporate gas in the static analysis tool set I execute in the CI chain of my projects. It could be nice if gas can generate reports in Checkstyle (XML) format. 
Did you have plans to generate Checkstyle-compatible results?
If you think it will nice to have checkstyle-format outpus, I can implement that micro-feature.

Regards,

**Comment by gcmurphy** [comment]
I'm not going to have time to work on this myself but I'd love to see it as a PR if you're still interested.
