### ISSUE TITLE
The skip option does not work properly

### ISSUE THREAD

**Issue by cosmincojocar** [GoASTScanner/gas#124]
I tired the following combinations to skip the vendor folder but none of them was successful:

gas -skip vendor ./...
gas -skip vendor/* ./...
gas -skip \*vendor\* ./...
gas -skip vendor/*.go ./...

The vendor folder was always included into the scan.

**Comment by gcmurphy** [comment]
The [changes here]( https://github.com/GoASTScanner/gas/blob/experimental/cmd/gas/main.go#L201) will address this. Effectively GAS _only_ scans complete packages, not individual files. By default it excludes the vendor directory and the files returned by a [built package](https://golang.org/src/go/build/build.go#L390) This will automatically exclude test files.
