### ISSUE TITLE
Incorrect line number reported

### ISSUE THREAD

**Issue by stevenh** [GoASTScanner/gas#131]
Gas reports the line number as the first line when reporting statements which span multiple lines.
```go

sql := `
    SELECT x
    FROM tbl
    WHERE x.col = ?` + criteria
```

In the above example gas reports  the line starting with ```sql := ``` instead of ```WHERE...``` this breaks gometalinter tailing comment no lint option e.g.

```go

sql := `
    SELECT x
    FROM tbl
    WHERE x.col = ?` + criteria // nolint: gas
```

**Comment by gcmurphy** [comment]
gas current reports a line range. i'm not sure if metalinter can handle this..but if it still is causing issues you could add `// #nosec` and gas will not report that error. 

```
➜  gas git:(experimental) ✗ ./gas -fmt=csv ../goo 2>/dev/null
/Users/grantmurphy/go/src/github.com/GoASTScanner/goo/main.go,12-15,SQL string concatenation,MEDIUM,HIGH,"`
    SELECT x
    FROM tbl
    WHERE x.col = ?` +  os.Args[1]"
```
