### ISSUE TITLE
can't find import for all imports

### ISSUE THREAD

**Issue by eiais** [GoASTScanner/gas#143]
a bunch of lines that look like this when running `gas -skip=vendor -skip=*/*_test.go -skip=*/*/*_test.go -fmt=csv -out=gas_output.csv ./...`
```
[gas] 2017/11/01 20:40:09 Processing "/go/src/github.com/theupdateframework/notary/client/errors.go"...
[gas] 2017/11/01 20:40:09 Error during type checking: "/go/src/github.com/theupdateframework/notary/client/errors.go:6:2: could not import github.com/theupdateframework/notary/tuf/data (can't find import: github.com/theupdateframework/notary/tuf/data)"
```

**Comment by jimmiebtlr** [comment]
I'm seeing many of these when using gas via gometalinter, think it's probably the same issue.

**Comment by gcmurphy** [comment]
gometalinter uses a vendored version of gas.. but this was the bug that resulted in me completely re-writing the way gas loads and scans packages to be more closely in alignment with the compiler toolchain.  i just merged that change so you should see this error go away if you update.
