### ISSUE TITLE
Even though scan ran successfully, the exit code is 1.

### ISSUE THREAD

**Issue by vtiwari-ring** [GoASTScanner/gas#155]
I'm running a CI job using gas scan, I found that even though scans run successfully and save the output in json, the exit code is still 1, Which is failing my CI job in development pipeline.

```
poothepanda:~ panda$ gas -fmt=json -log=/tmp/newgaslog.log -out=/Users/poothepanda/gasscan.json projects/social-consumer/
2018/01/22 14:43:50 including rules: default
2018/01/22 14:43:50 excluding rules: default
poothepanda:~ panda$ echo $?
1
```

**Comment by gcmurphy** [comment]
If gas detects any issues it will return a non-zero exit code.

**Comment by gcmurphy** [comment]
Closing as no response.
