### ISSUE TITLE
JUnit XML output format

### ISSUE THREAD

**Issue by wongherlung** [GoASTScanner/gas#158]
Hi,

I've integrate gas into my CI workflow, which requires JUnit XML formatted results. Currently, I've created a simple program to parse the `json` output from gas into Junit XML, which I thought it would be nice as an enhancement for gas.

Would it be okay if I do a PR to implement an option to output the results in Junit XML? Also there is an issue of multiple types of XML format, as mentioned in #120. What are your thoughts on this if we were to implement `xml` format for gas?

**Comment by gcmurphy** [comment]
Sounds like a great addition I look forward to the PR. There shouldn't be any problem with multiple XML formats, we could name one as -junit and the other -checkstyle if it became confusing.

**Comment by gcmurphy** [comment]
Fixed by #160
