### ISSUE TITLE
Quiet do not suppress log output

### ISSUE THREAD

**Issue by Crevil** [GoASTScanner/gas#196]
### Summary 
The `-quiet` flag documentation specifies the following
```
-quiet
    Only show output when errors are found
```

I do not find that to be the case though. When running with the flag `gas` still outputs log lines for what directories search etc. I do see the `results` summarice disappear with the flag.

On larger projects, these log lines pollute the output a lot and make it harder to actually know what to expect of the command.

### Steps to reproduce the behavior

Create a package in your GOPATH with a single file in
```go
package t
```

Run `gas` with quiet flag

```
gas -quiet ./...
```

### Gas version
Git revision: `542d0c0e4fb652d0b5b0a1241c44733d07b78e71`

### Go version (output of 'go version')
` version go1.9.2 darwin/amd64`

### Operating system / Environment
macOS 10.13.3

### Expected behavior
Expected output to be empty

### Actual behavior
Output was
```
[gas] 2018/03/26 11:41:12 including rules: default
[gas] 2018/03/26 11:41:12 excluding rules: default
[gas] 2018/03/26 11:41:12 Searching directory: <$GOPATH>/src/github.com/Crevil/gas-test
[gas] 2018/03/26 11:41:12 Checking package: t
[gas] 2018/03/26 11:41:12 Checking file: <$GOPATH>/src/github.com/Crevil/gas-test/t.go
```

**Comment by Shikkic** [comment]
+1
