### ISSUE TITLE
Can't understand warning (Subprocess launching should be audited.,LOW,HIGH)

### ISSUE THREAD

**Issue by Its-Alex** [GoASTScanner/gas#204]
Hi I have a problem with gas this return `Subprocess launching should be audited.,LOW,HIGH` and I can't find why

```
       cmd := exec.Command("/usr/bin/ffprobe",
		"-v", "quiet",
		"-print_format", "json",
		"-show_format",
		"-show_streams",
		"-",
	)
	cmd.Stdin = d.GetNormalReader()
	res, err := cmd.Output()
	if err != nil {
		log.WithError(err).Error("Cannot start ffprobe")
		return nil
	}
	log.Debug(string(res))
	err = json.Unmarshal(res, &transcoder.probe)
	if err != nil {
		log.WithError(err).Error("Cannot parse JSON from ffprobe")
		return nil
	}
```

I use gas 2.0 and go 1.10 under linux

**Comment by gcmurphy** [comment]
I agree the subprocess rule is a little confusing. Shelling out can lead to some unintended security consequences so we want to alert users to check that. So in this case 'should be audited' means make sure you've done a code review and are sure there isn't a potential command injection vector here. 

Go does a fairly good job of sanitising inputs, but it can be useful to be warned about things. For example user can execute arbitrary commands here: 

```go
package main

import (
	"bytes"
	"fmt"
	"os/exec"
)

func main() {

	var out bytes.Buffer

	// suppose this was user controlled
	usersInput := "cat /etc/passwd"

	cmd := exec.Command("/bin/bash", "-c", usersInput)
	cmd.Stdout = &out
	err := cmd.Run()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(out.String())
}
```

The subprocess rule does need improvement, and I think in general I need to provide better documentation for all rules.  I'll work on doing that. 

Does this help answer your question?

**Comment by Its-Alex** [comment]
Yes, this answer helped me thank you a lot for my case.
I agree with a little documentation about rules because it's hard to understand some rule.

**Comment by Suteng364** [comment]
> I agree the subprocess rule is a little confusing. Shelling out can lead to some unintended security consequences so we want to alert users to check that. So in this case 'should be audited' means make sure you've done a code review and are sure there isn't a potential command injection vector here.
> 
> Go does a fairly good job of sanitising inputs, but it can be useful to be warned about things. For example user can execute arbitrary commands here:
> 
> ```go
> package main
> 
> import (
> 	"bytes"
> 	"fmt"
> 	"os/exec"
> )
> 
> func main() {
> 
> 	var out bytes.Buffer
> 
> 	// suppose this was user controlled
> 	usersInput := "cat /etc/passwd"
> 
> 	cmd := exec.Command("/bin/bash", "-c", usersInput)
> 	cmd.Stdout = &out
> 	err := cmd.Run()
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 	fmt.Println(out.String())
> }
> ```
> 
> The subprocess rule does need improvement, and I think in general I need to provide better documentation for all rules. I'll work on doing that.
> 
> Does this help answer your question?

What does the code mean? I want to know how to fix rule_id G204 and the details is Subprocess launched with variable

**Comment by haroldHT** [comment]
So is there any right example to solve G204？
