### ISSUE TITLE
Incorrect warning about weak crypto

### ISSUE THREAD

**Issue by ptman** [GoASTScanner/gas#43]
Running gas 37205e9afa56150a634a1d0d19347446e9b27f17 I get:

```
[foo.go:411] - Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
  > rand.Read(buf)
```

The file in question imports `math/rand` as `mrand` and `crypto/rand` as `rand`:

```
import (
    "crypto/rand"
    mrand "math/rand"
```

So the line in question is actually using crypto/rand, and not math/rand.

**Comment by gcmurphy** [comment]
I'm going to close this now as I believe it's resolved. Thanks @tam7t for helping getting a working solution here.
