### ISSUE TITLE
G104 whitelisting

### ISSUE THREAD

**Issue by wttw** [GoASTScanner/gas#54]
There are some functions that do return an error but are guaranteed to always return nil - so checking for errors is somewhere between pointless and a sign of risky program logic.

It'd be nice to be able to whitelist functions rather than having to annotate, e.g., every use of bytes.Buffer.Write() individually.

**Comment by tam7t** [comment]
I would second this as a useful feature and suggest maybe drawing inspiration from [brakeman](http://brakemanscanner.org/docs/ignoring_false_positives/).

**Comment by gcmurphy** [comment]
Ok. Will look at adding this. For isolated instances you can always add the '// #nosec' annotation to ignore.

**Comment by gcmurphy** [comment]
I've made some progress here in PR https://github.com/GoASTScanner/gas/pull/92.

- Added the ability to add custom whitelists via config file. 
- Fixed rule so in addition to assignment to '_', errors that are implicitly ignored will also be reported. 

The problem now becomes that this rule will be even more noisy. I'm considering switching from a whitelist to a blacklist of calls that you _should_ check to avoid security issues, however coming up with that list could be difficult also. 

@wttw @tam7t how would you prefer this works?
