### ISSUE TITLE
Exclude Rule Not Working

### ISSUE THREAD

**Issue by mccabe615** [GoASTScanner/gas#57]
I'm running the following command trying to exclude the hardcoded credentials finding but the finding is still being flagged.

```
gas -exclude=G101 ./folder/*.go
```

**Comment by gcmurphy** [comment]
Are you able to provide more details on the example? This example works as expected for me


```
➜  gas git:(master) cat /tmp/*.go
package main

import "fmt"

func main() {
	username := "admin"
	password := "admin"
	fmt.Println("Doing something with: ", username, password)
}
➜  gas git:(master) ./gas  /tmp/*.go 
0
Results:

[/tmp/sample.go:7] - Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
  > password := "admin"


Summary:
   Files: 1
   Lines: 9
   Nosec: 0
  Issues: 1


➜  gas git:(master) ./gas -exclude=G101 /tmp/*.go
0
Results:

Summary:
   Files: 1
   Lines: 9
   Nosec: 0
  Issues: 0

```

**Comment by mccabe615** [comment]
Here are a few more details

```
/tmp ❯❯❯ cat f.go
package main

import "fmt"

func main() {
       	password, passwordErr := models.FindPasswordReset(db, request.Id)
}
/tmp ❯❯❯ gas -exclude=G101 f.go
Results:

[f.go:6] - Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
  > password, passwordErr := models.FindPasswordReset(db, request.Id)


Summary:
   Files: 1
   Lines: 7
   Nosec: 0
  Issues: 1
```

```
/tmp ❯❯❯ go version
go version go1.6 darwin/amd64
```

**Comment by gcmurphy** [comment]
I'm having a tough time reproducing this. Is your test on latest master? 

This type of thing is a perfect example of why I need to embed version information so I'm going to create a bug for that.

**Comment by mccabe615** [comment]
After updating go and pulling down the latest version it no longer flags my example.

```
~/c/ ❯❯❯ cat f.go
package main

import "fmt"

func main() {
        password, passwordErr := models.FindPasswordReset(db, request.Id)
}
~/c/❯❯❯ gas f.go
Results:

Summary:
   Files: 1
   Lines: 7
   Nosec: 0
  Issues: 0

```

**Comment by gcmurphy** [comment]
Thanks. I'm going to close this for now but will be revisiting the hardcoded password logic in a separate issue. Hopefully if there was an issue I'll uncover it as a part of that work.  Thanks for the bug report anyway.

**Comment by mccabe615** [comment]
Sounds good. Any idea why it wouldn't flag the example above now when not including the exclude flag?

**Comment by gcmurphy** [comment]
At the moment we look for secrets that are directly hardcoded in your program but the logic is pretty low tech. We examine assign statements and look for constants or string literals on the right hand side.  So we can detect this kind of thing:   

```go
username := "admin"
password := "secret"
sessionId := login(username, password) 
```

But not really the example you provided. There is still much work needed to be done to improve the existing rules 😄

**Comment by mccabe615** [comment]
Gotcha. Thanks for your work!
