### ISSUE TITLE
Initialization import false positives

### ISSUE THREAD

**Issue by iambrosie** [GoASTScanner/gas#59]
According to [the reference](https://golang.org/ref/spec#Import_declarations), 

> To import a package solely for its side-effects (initialization), use the blank identifier as explicit package name: 
`import _ "lib/math"`

However, if I run gas against the following piece of code
```
package main

import (
	_ "crypto/md5"
	"fmt"
)

func main() {
	fmt.Println("MD5 is not used here")
}
```

I will get the following output

> iambrosie@xxx:~/Documents/GoCode/src/github.com/iambrosie/weakcrypto$ gas main.go 
> 0
> Results:
> 
> [main.go:4] - Use of weak cryptographic primitive (Confidence: HIGH, Severity: HIGH)
>   \> _ "crypto/md5"
> 
> Summary:
>    Files: 1
>    Lines: 10
>    Nosec: 0
>   Issues: 1

**Comment by gcmurphy** [comment]
Thanks. We are looking at using the typechecker to resolve this class of bug.
