### ISSUE TITLE
Broken imports, add lint, vet, fmt, etc...

### ISSUE THREAD

**Issue by endophage** [GoASTScanner/gas#61]
Looks really bad when a code quality tool doesn't have checks running against its own PRs. Currently problem due to the following error:

```
# github.com/HewlettPackard/gas
src/github.com/HewlettPackard/gas/rulelist.go:18: imported and not used: "fmt"
```

**Comment by gcmurphy** [comment]
Sorry. We just migrated from that location and haven't updated the imports. I will fix now.

**Comment by endophage** [comment]
Also looks like that wasn't PR'd but was committed directly to master :-(

**Comment by gcmurphy** [comment]
Added go vet to travis-ci and also to re-add travis to new organization. 

853b0979225e39fb3c9141942d6c0e021c47ca34

Appreciate the feedback.
